spring:
  profiles.active: default

---

spring:
  profiles: default

server:
  port: 8081

database:
  driverName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/drivers
  username: postgres
  password: postgres
  hibernateDialect: org.hibernate.dialect.PostgreSQL94Dialect
  hibernateShowSql: true
  hibernateHbm2ddl: create
